all: dev sys utils cmds

dev:
    make -C lib
    make -C utils/as
    make -C utils/cc
    make -C utils/ar
    make -C utils/make
    make -C utils/impdef

sys:
    make -C sys

utils:
    make -C utils/edit
    make -C utils/fdisk
    make -C utils/login
    make -C utils/mkboot
    make -C utils/genvmdk
    make -C utils/setup
    make -C utils/sh

cmds:
    make -C cmds

install: install-dev install-sys install-utils install-cmds

install-dev:
    make -C lib install
    make -C utils/as install
    make -C utils/cc install
    make -C utils/ar install
    make -C utils/make install
    make -C utils/impdef install

install-sys:
    make -C sys install

install-utils:
    make -C utils/edit install
    make -C utils/fdisk install
    make -C utils/login install
    make -C utils/mkboot install
    make -C utils/genvmdk install
    make -C utils/setup install
    make -C utils/sh install

install-cmds:
    make -C cmds install

cross:
    make -C sys cross
    make -C lib cross
    make -C utils/as cross
    make -C utils/cc cross
    make -C utils/ar cross
    make -C utils/make cross
    make -C utils/impdef cross
    make -C utils/edit cross
    make -C utils/fdisk cross
    make -C utils/login cross
    make -C utils/mkboot cross
    make -C utils/genvmdk cross
    make -C utils/setup cross
    make -C utils/sh cross
    make -C cmds cross

clean: clean-dev clean-sys clean-utils clean-cmds

clean-dev:
    make -C lib clean
    make -C utils/as clean
    make -C utils/cc clean
    make -C utils/ar clean
    make -C utils/make clean
    make -C utils/impdef clean

clean-sys:
    make -C sys clean

clean-utils:
    make -C utils/edit clean
    make -C utils/fdisk clean
    make -C utils/login clean
    make -C utils/mkboot clean
    make -C utils/genvmdk clean
    make -C utils/setup clean
    make -C utils/sh clean

clean-cmds:
    make -C cmds clean

.PHONY: utils sys cmds
