name: "CI"
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  schedule:
    - cron: '43 15 * * 3'
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'COMPILE'
      shell: bash
      run: |
        sudo apt-get update -y && sudo apt-get install -y gcc-multilib libc6-dev-i386 genisoimage
        make
    - name: 'BUILD (CDROM)''
      shell: bash
      run: |
        make krlean cdrom
    - name: 'BUILD (FLOPPY)'
      shell: bash
      run: |
        make krlean floppy
    - name: 'BUILD (VMDK)'
      shell: bash
      run: |
        make krlean vmdk
    - name: 'CLEAN'
      shell: bash
      run: |
        make clean