name: "CI"
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'COMPILE'
      shell: bash
      run: |
        sudo apt-get update -y && sudo apt-get install -y gcc-multilib libc6-dev-i386 genisoimage
        make krlean
    - name: 'BUILD (CDROM)'
      shell: bash
      run: |
        make cdrom
    - name: 'BUILD (FLOPPY)'
      shell: bash
      run: |
        make floppy
    - name: 'BUILD (VMDK)'
      shell: bash
      run: |
        make vmdk
    - name: 'CLEAN'
      shell: bash
      run: |
        make clean